spring.cloud.gateway.routes.user-service.id=user-service
spring.cloud.gateway.routes.user-service.uri=http://localhost:8081
spring.cloud.gateway.routes.user-service.predicates[0]=Path=/users/**,/api/users/**
spring.cloud.gateway.routes.user-service.filters[0]=StripPrefix=1

spring.cloud.gateway.routes.product-service.id=product-service
spring.cloud.gateway.routes.product-service.uri=http://localhost:8082
spring.cloud.gateway.routes.product-service.predicates[0]=Path=/products/**,/api/products/**
spring.cloud.gateway.routes.product-service.filters[0]=StripPrefix=1

spring.cloud.gateway.routes.auth-service.id=auth-service
spring.cloud.gateway.routes.auth-service.uri=http://localhost:8083
spring.cloud.gateway.routes.auth-service.predicates[0]=Path=/auth/**