server.port=8080
spring.application.name=api-gateway

# Conexión con Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Rutas usando Service Discovery (lb://)
spring.cloud.gateway.routes[0].id=comment-service
spring.cloud.gateway.routes[0].uri=lb://comment-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/comments/**,/api/comments/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**,/api/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1